import * as vscode from "vscode";
import type { PasteSource } from "@protege/types";
import { getBatcher } from "./batcher.js";

/**
 * Heuristic paste classifier. VS Code doesn't expose "this change came
 * from a paste" directly, so we approximate: any single-edit change that
 * inserts >= MIN_PASTE_CHARS and contains a newline or long contiguous
 * run is treated as a paste. Source class is inferred by comparing the
 * pasted content to the most recent clipboard snapshot.
 */

const MIN_PASTE_CHARS = 40;
const AI_MARKERS = [
  // Common AI-chat output markers users paste out of Claude/ChatGPT etc.
  /^```[a-z]*$/im,
  /^\/\/ ?Generated by/i,
  /^\/\* Generated/i,
];

let lastClipboardText = "";

async function refreshClipboardSnapshot(): Promise<void> {
  try {
    lastClipboardText = await vscode.env.clipboard.readText();
  } catch {
    // Clipboard can be unavailable in remote workspaces — ignore.
  }
}

function classify(pasted: string): PasteSource {
  const trimmed = pasted.trim();
  if (!trimmed) return "self-edit-paste";
  if (lastClipboardText && trimmed === lastClipboardText.trim()) {
    // Clipboard match — came from our own copy or a system-wide copy.
    // Without AI-source disambiguation we default to external.
    return "external";
  }
  for (const m of AI_MARKERS) {
    if (m.test(trimmed)) return "ai-chat-output";
  }
  // Heuristic: long blocks with balanced brackets → likely AI output.
  if (trimmed.length > 240 && /[{}]/.test(trimmed) && /\n/.test(trimmed)) {
    return "ai-chat-output";
  }
  return "external";
}

export function startPasteClassifier(
  context: vscode.ExtensionContext
): vscode.Disposable {
  void refreshClipboardSnapshot();
  const subscriptions: vscode.Disposable[] = [];

  subscriptions.push(
    vscode.workspace.onDidChangeTextDocument((e) => {
      if (e.document.uri.scheme !== "file") return;
      for (const change of e.contentChanges) {
        if (!change.text) continue;
        if (change.text.length < MIN_PASTE_CHARS) continue;
        if (change.rangeLength > 0) continue; // replacement, not pure insert
        if (!/\n|\t{2,}|\s{4,}/.test(change.text)) continue;
        const source = classify(change.text);
        const b = getBatcher();
        if (b) {
          b.push({
            type: "paste_classified",
            ts: Date.now(),
            file: e.document.fileName,
            source,
            chars: change.text.length,
          });
        }
      }
      // Refresh the clipboard snapshot opportunistically — done on every
      // change tick so the next paste can be compared accurately.
      void refreshClipboardSnapshot();
    })
  );

  const disposable = new vscode.Disposable(() => {
    for (const s of subscriptions) s.dispose();
  });
  context.subscriptions.push(disposable);
  return disposable;
}
