-- =============================================================
-- Migration 004 — Revoke anon grants on legacy tables.
-- =============================================================
--
-- Apply once against the live Supabase project. Idempotent — safe
-- to re-run.
--
--   psql "$SUPABASE_DB_URL" -f apps/backend/migrations/004_revoke_anon_legacy_tables.sql
--
-- Background:
--
-- Tables created before migration 003 (the beta-sync tables) were
-- created without explicit grant management. Postgres' default behaviour
-- on a fresh table created via the Supabase SQL editor (or generated by
-- supabase-js) leaves the table accessible to `anon` and
-- `authenticated`. RLS is enabled on every table so writes are still
-- effectively denied (RLS-enabled + no policies = deny-by-default), but
-- the explicit grant residue is a defence-in-depth gap: any future
-- accidental policy that does `USING (true)` would silently expose data.
--
-- Locking these down explicitly so the only path that can read or write
-- to them is the backend authenticating as `service_role`.
--
-- Caught by the best-practices audit on 2026-04-30 (53 pass · 11 warn).
-- =============================================================

BEGIN;

-- Tables that pre-date migration 003 and need their anon/authenticated
-- grants stripped.
DO $$
DECLARE
  t TEXT;
  legacy TEXT[] := ARRAY[
    'users',
    'concepts',
    'concept_statuses',
    'concept_encounters',
    'gains',
    'echo_events',
    'behavior_daily_rollups',
    'file_authorship_counters',
    'line_rewrite_counters',
    'commit_stories',
    'repo_concept_index'
  ];
BEGIN
  FOREACH t IN ARRAY legacy LOOP
    -- Only act if the table actually exists. Keeps the migration safe
    -- on a fresh project where the legacy tables were never created.
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = t
    ) THEN
      EXECUTE format('REVOKE ALL ON %I FROM PUBLIC', t);
      EXECUTE format('REVOKE ALL ON %I FROM anon', t);
      EXECUTE format('REVOKE ALL ON %I FROM authenticated', t);
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO service_role',
        t
      );
    END IF;
  END LOOP;
END $$;

-- Note: leaderboard is a view, not a table — handled separately.
-- Views inherit access from underlying tables; revoking on `users` and
-- `concepts` already locks the view down. Re-grant SELECT to
-- service_role so the backend's getLeaderboard() call still works.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.views
    WHERE table_schema = 'public' AND table_name = 'leaderboard'
  ) THEN
    EXECUTE 'REVOKE ALL ON leaderboard FROM PUBLIC';
    EXECUTE 'REVOKE ALL ON leaderboard FROM anon';
    EXECUTE 'REVOKE ALL ON leaderboard FROM authenticated';
    EXECUTE 'GRANT SELECT ON leaderboard TO service_role';
  END IF;
END $$;

COMMIT;
